library(ggplot2)
library(dplyr)
library(plyr)
library(depmixS4)
library(reshape2)

print(bicplot(sumdat))
print(avgplot(simdat))
print(acfplot(simdat))
print(msd45(fitsin4s,fithomo5s))
print(avgplot(vitcat(cat,fithomo3s)))
print(avgplot(vitcat(cat,fitsin3s)))
print(avgplot(vitcat5(cat,fithomo5s)))
print(avgplot(vitcat5(cat,fitsin5s)))
print(acfplot(vitcat(cat,fithomo3s))+ggtitle("Viterbi vs Observed ACF"))
print(acfplot(vitcat5(cat,fitsin5s))+ggtitle("Viterbi vs Observed ACF"))

